name: Android CI

on:
  pull_request:
    branches-ignore:
      - 'l10n_v3_openjdk'
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'l10n_v3_openjdk'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
